name: MySQL Tests
on: 
  push:
  pull_request:
  repository_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install
        run: |
          pip3 install           \
            black==25.1.0        \
            clang_format==11.0.1 \
            cmake-format==0.6.13

      - name: Format Check
        run: |
          python -m pip show black
          python -m pip show cmake_format
          python -m pip show clang_format
          clang-format --version
          clang-format --dump-config
          make format-check

  linux:
    name: Linux MySQL (amd64)
    runs-on: ubuntu-latest
    needs: format-check
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      CCACHE_DIR: ${{ github.workspace }}/ccache
      VCPKG_TARGET_TRIPLET: x64-linux-release
      VCPKG_HOST_TRIPLET: x64-linux-release
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      MYSQL_PWD: root

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Install required ubuntu packages
      run: |
        sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
        sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
          build-essential \
          ccache \
          cmake \
          ninja-build

    - name: Cache Key
      id: cache_key
      working-directory: ./duckdb
      run: |
        DUCKDB_VERSION=$(git rev-parse --short=10 HEAD)
        KEY="${{ runner.os }}-${{ runner.arch }}-$DUCKDB_VERSION"
        echo "value=${KEY}" >> "${GITHUB_OUTPUT}"

    - name: Restore Cache
      uses: actions/cache/restore@v5
      with:
        path: ${{ github.workspace }}/ccache
        key: ${{ steps.cache_key.outputs.value }}

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: 9e593bb18ea69cc5095e012465dcd675a822ed0d # Release 2026.07.29

    - name: Build extension
      run: |
        make release

    - name: Save Cache
      uses: actions/cache/save@v5
      with:
        path: ${{ github.workspace }}/ccache
        key: ${{ steps.cache_key.outputs.value }}

    - name: Setup MySQL
      run: |
        sudo systemctl start mysql
        sudo systemctl status mysql
        echo "[client]" >> ~/.my.cnf
        echo "default-character-set = utf8mb4" >> ~/.my.cnf
        mysql -u root -e "SET GLOBAL wait_timeout = 28800; SET GLOBAL interactive_timeout = 28800; SET GLOBAL net_read_timeout = 300; SET GLOBAL net_write_timeout = 300"
        mysql -u root < test/test_data.sql
        mysql -u root -e "SELECT 42"

    - name: Test extension
      env: 
        LOCAL_EXTENSION_REPO: ${{ github.workspace }}/build/release/repository/
        MYSQL_TEST_DATABASE_AVAILABLE: 1
        ORACLE_MYSQL_SERVER: 1
      run: |
        ./build/release/test/unittest 'test/*'

  linux-mariadb:
    name: Linux MariaDB (amd64)
    runs-on: ubuntu-latest
    needs: linux
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      CCACHE_DIR: ${{ github.workspace }}/ccache
      VCPKG_TARGET_TRIPLET: x64-linux-release
      VCPKG_HOST_TRIPLET: x64-linux-release
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      MYSQL_PWD: root

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: 'true'

    - name: Install required ubuntu packages
      run: |
        sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
        sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
          build-essential \
          ccache \
          cmake \
          mariadb-server \
          ninja-build \
          pkg-config \
          zip

    - name: Cache Key
      id: cache_key
      working-directory: ./duckdb
      run: |
        DUCKDB_VERSION=$(git rev-parse --short=10 HEAD)
        KEY="${{ runner.os }}-${{ runner.arch }}-$DUCKDB_VERSION"
        echo "value=${KEY}" >> "${GITHUB_OUTPUT}"

    - name: Restore Cache
      uses: actions/cache/restore@v5
      with:
        path: ${{ github.workspace }}/ccache
        key: ${{ steps.cache_key.outputs.value }}

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: 9e593bb18ea69cc5095e012465dcd675a822ed0d # Release 2026.07.29

    - name: Build extension
      run: |
        make release

    - name: Setup MariaDB
      run: |
        sudo mariadb -e "select @@version"
        sudo mariadb -e "ALTER USER root@localhost IDENTIFIED BY 'root'"
        echo "[client]" >> ~/.my.cnf
        echo "default-character-set = utf8mb4" >> ~/.my.cnf
        mysql -u root -e "SET GLOBAL wait_timeout = 28800; SET GLOBAL interactive_timeout = 28800; SET GLOBAL net_read_timeout = 300; SET GLOBAL net_write_timeout = 300"
        mysql -u root < test/test_data.sql
        mysql -u root -e "SELECT 42"

    - name: Test extension
      env: 
        LOCAL_EXTENSION_REPO: ${{ github.workspace }}/build/release/repository/
        MYSQL_TEST_DATABASE_AVAILABLE: 1
        MARIADB_SERVER: 1
      run: |
        ./build/release/test/unittest 'test/*'

  linux-sanitized:
    name: Linux ${{ matrix.sanitizer.name }} (amd64)
    needs: linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sanitizer:
        - name: ASan
          threadsan_enabled: 0
        - name: TSan
          threadsan_enabled: 1

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      CCACHE_DIR: ${{ github.workspace }}/ccache
      VCPKG_TARGET_TRIPLET: x64-linux-release
      VCPKG_HOST_TRIPLET: x64-linux-release
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      MYSQL_PWD: root

    steps:

    - name: Free disk space
      uses: endersonmenezes/free-disk-space@v2.1.1
      continue-on-error: true
      with:
        remove_haskell: true
        remove_tool_cache: true
        remove_folders: "/usr/local/share/powershell /usr/share/swift"
        testing: false

    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: 'true'

    - name: Install required ubuntu packages
      run: |
        sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
        sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
          build-essential \
          ccache \
          cmake \
          mold

    - name: Cache Key
      id: cache_key
      working-directory: ./duckdb
      run: |
        DUCKDB_VERSION=$(git rev-parse --short=10 HEAD)
        KEY="${{ runner.os }}-${{ runner.arch }}-$DUCKDB_VERSION"-relassert-${{ matrix.sanitizer.name }}
        echo "value=${KEY}" >> "${GITHUB_OUTPUT}"

    - name: Restore Cache
      uses: actions/cache/restore@v5
      with:
        path: ${{ github.workspace }}/ccache
        key: ${{ steps.cache_key.outputs.value }}

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: 9e593bb18ea69cc5095e012465dcd675a822ed0d # Release 2026.07.29

    - name: Build extension
      env:
        THREADSAN: ${{ matrix.sanitizer.threadsan_enabled }}
      run: |
        make relassert
        grep -m 1 fsanitize ./build/relassert/build.ninja

    - name: Save Cache
      uses: actions/cache/save@v5
      with:
        path: ${{ github.workspace }}/ccache
        key: ${{ steps.cache_key.outputs.value }}

    - name: Setup MySQL
      run: |
        sudo systemctl start mysql
        sudo systemctl status mysql
        echo "[client]" >> ~/.my.cnf
        echo "default-character-set = utf8mb4" >> ~/.my.cnf
        mysql -u root -e "SET GLOBAL wait_timeout = 28800; SET GLOBAL interactive_timeout = 28800; SET GLOBAL net_read_timeout = 300; SET GLOBAL net_write_timeout = 300"
        mysql -u root < test/test_data.sql
        mysql -u root -e "SELECT 42"

    - name: Test extension
      env: 
        LOCAL_EXTENSION_REPO: ${{ github.workspace }}/build/relassert/repository/
        MYSQL_TEST_DATABASE_AVAILABLE: 1
        ORACLE_MYSQL_SERVER: 1
      run: |
        ./build/relassert/test/unittest
